[package]
name = "lacec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
logos = "0.12.0"
colored = "2.0.0"
bincode = "1.3.3"
serde = { version = "1.0.33", features = ["derive"] }
